In [1]:
import os
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.compose import (
    ColumnTransformer,
    TransformedTargetRegressor,
    make_column_transformer,
)
from sklearn.dummy import DummyRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.impute import SimpleImputer
from sklearn.linear_model import Ridge, RidgeCV
from sklearn.metrics import make_scorer, mean_squared_error, r2_score
from sklearn.model_selection import (
    GridSearchCV,
    cross_val_score,
    cross_validate,
    train_test_split,
)
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, StandardScaler
from sklearn.tree import DecisionTreeRegressor

In [8]:
# Split into train and test
df = pd.read_csv("Data/sales.csv")
train_df, test_df = train_test_split(df, test_size=0.20, random_state=123)
train_df.head()

,type,likes,num_comments,num_shares,days_from_event,revenue,total_transactions,collab,date,num_posts,memberships_sold,pop,popcorn_large,popcorn_medium,popcorn_small,Alcohol,general_promo_likes,general_promo_shares,type_post,candy
9,Regular screening,94.0,3.0,16.0,2.0,11.83,4.0,No,30/09/2025,2,1.0,3.0,0.0,0.0,0.0,0.0,82.0,14.0,both,0.0
78,Regular screening,148.0,3.0,43.0,2.0,60.32,16.0,No,30/03/2026,2,4.0,8.0,1.0,5.0,1.0,0.0,131.0,58.0,both,0.0
79,Special w/UBC Club,70.0,2.0,26.0,4.0,128.32,27.0,Yes,02/04/2026,2,4.0,13.0,8.0,8.0,0.0,3.0,131.0,58.0,both,0.0
28,Regular screening,55.0,0.0,7.0,2.0,56.15,9.0,No,10/11/2025,2,5.0,2.0,0.0,3.0,3.0,0.0,53.0,14.0,both,4.0
60,Special w/UBC Club,249.0,8.0,54.0,5.0,27.66,7.0,Yes,04/02/2026,2,2.0,0.0,0.0,4.0,2.0,0.0,108.0,51.0,both,0.0

In [9]:
# Split target value
X_train = train_df.drop(columns=["revenue"])
y_train = train_df["revenue"]

X_test = test_df.drop(columns=["revenue"])
y_test = test_df["revenue"]

In [10]:
train_df.describe()

,likes,num_comments,num_shares,days_from_event,revenue,total_transactions,num_posts,memberships_sold,pop,popcorn_large,popcorn_medium,popcorn_small,Alcohol,general_promo_likes,general_promo_shares,candy
count,65.000000,65.000000,65.000000,65.000000,67.000000,67.000000,68.000000,67.000000,67.000000,67.000000,67.000000,67.000000,67.000000,59.000000,59.000000,67.000000
mean,143.492308,2.261538,79.861538,3.230769,132.639104,25.835821,1.867647,8.567164,8.522388,3.567164,4.686567,2.447761,3.776119,107.932203,54.898305,0.731343
std,84.257812,2.538928,114.441289,2.422352,184.630017,32.141542,0.419823,15.404863,9.178958,5.535625,6.348965,7.958764,13.666838,63.077911,64.238697,2.019467
min,22.000000,0.000000,3.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,46.000000,0.000000,0.000000
25%,77.000000,0.000000,20.000000,2.000000,21.000000,6.000000,2.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,69.500000,15.000000,0.000000
50%,114.000000,1.000000,38.000000,2.000000,57.980000,12.000000,2.000000,3.000000,5.000000,1.000000,3.000000,0.000000,0.000000,95.000000,34.000000,0.000000
75%,205.000000,4.000000,113.000000,3.000000,148.555000,27.500000,2.000000,7.000000,11.000000,4.500000,5.500000,2.500000,0.000000,119.000000,55.500000,0.000000
max,413.000000,11.000000,756.000000,13.000000,827.540000,128.000000,3.000000,74.000000,39.000000,26.000000,36.000000,63.000000,77.000000,288.000000,239.000000,10.000000